prSections:
    - title: My Pull Requests
      filters: is:open author:@me
    - title: Needs My Review
      filters: is:open review-requested:@me
    - title: Team Magritte
      filters: is:open team-review-requested:raidium-med/magritte
    - title: Curia
      filters: is:open team-review-requested:raidium-med/curia-review
    - title: Involved
      filters: is:open involves:@me -author:@me
repo:
    branchesRefetchIntervalSeconds: 30
    prsRefetchIntervalSeconds: 60
defaults:
    preview:
        open: true
        width: 150
    prsLimit: 20
    prApproveComment: LGTM
    issuesLimit: 20
    view: prs
    layout:
        prs:
            updatedAt:
                width: 5
            createdAt:
                width: 5
            repo:
                width: 20
            author:
                width: 15
            authorIcon:
                hidden: false
            assignees:
                width: 20
                hidden: true
            base:
                width: 15
                hidden: true
            lines:
                width: 15
        issues:
            updatedAt:
                width: 5
            createdAt:
                width: 5
            repo:
                width: 15
            creator:
                width: 10
            creatorIcon:
                hidden: false
            assignees:
                width: 20
                hidden: true
    refetchIntervalMinutes: 30
keybindings:
  prs:
    - key: g
      name: Lazygit
      command: lazygit -p {{.RepoPath}}
    - key: C
      name: Code Review
      command: cd {{.RepoPath}} && ~/nvim.appimage -c ":silent Octo pr edit {{.PrNumber}}"
repoPaths:
  raidium-med/rd: /home/julien.khlaut/rd
theme:
    colors:
        text:
            primary: "#cdd6f4"
            secondary: "#b4befe"
            inverted: "#11111b"
            faint: "#bac2de"
            warning: "#f9e2af"
            success: "#a6e3a1"
            error: "#f38ba8"
        background:
            selected: "#313244"
        border:
            primary: "#b4befe"
            secondary: "#45475a"
            faint: "#313244"
    ui:
      sectionsShowCount: true
      table:
          showSeparator: true
          compact: false
pager:
    diff: ""
confirmQuit: false
showAuthorIcons: true
smartFilteringAtLaunch: true
